export default {
  username: 'Username',
  password: 'Password',
  repeatPassword: 'Repeat password',
  email: 'Email',
  yourEmail: 'Your email',
  yourName: 'Your name',
  phone: 'Phone',
  login: 'Login',
  welcome: 'Welcome',
  change_language: 'Change Language',
  forgotPassword: 'Forgot your password?',
  loginWGoogleFB: 'Login with Google or Facebook',
  noAccount: "Don't have an account?",
  haveAccount: 'Already have an account?',
  signup: 'Sign up',
  phonePlaceholder: 'Your phone number',
  next: 'Next',
  skip: 'Skip',
  newAccount: 'Create new \naccount',
  addressPlaceholder: 'City or region',
  addPhoto: 'Add photo',
  completeRegisterTitle: 'Ready! Welcome to kibtop',
  completeRegisterDescription: 'Now you can place your ad \nor buy products',
  placeAd: 'Place ad',
  watchAds: 'Watch ads',
  invalidEmail: 'incorrect mail',
  requiredField: 'This is a required field',
  passwordNotMatch: 'Passwords do not match',
  passwordRecoveryHeader: 'Password \nrecovery',
  passwordRecoveryTitle: 'Ready! Check your email',
  passwordRecoveryText: 'We have sent a password \nreset link to your email',
  useMyLocation: 'Use my location',
  passwordValidationText: `
Your password can’t be too similar to your other personal information.
Your password must contain at least 8 characters.
Your password can’t be a commonly used password.
Your password can’t be entirely numeric.`,
}
