export default {
  title: 'Promote your products',
  text: 'Sell much faster and more profitably!',
  serviceSets: 'Service sets',
  separateServices: 'Separate services',
  easyStart: 'Easy start',
  topAd3: 'TOP ad for 3 days',
  topAd7: 'TOP ad for 7 days',
  topAd30: 'TOP ad for 30 days',
  days: 'days',
  quickSale: 'Quick sale',
  enable: 'Enable',
  for: 'for',
  lifts3: '3 lifts in the up issue',
  lifts9: '9 lifts in the up issue',
  turboSale: 'Turbo sale',
  vipAd7: 'VIP ad for 7 days',
  total: 'total',
}
